---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  - port: 16379
    targetPort: 16379
    name: cluster
  clusterIP: None
  selector:
    app: redis
